### ISSUE TITLE
Provide Nodes SSO login page

### ISSUE THREAD

**Issue by BrettRToomey** [nodes-vapor/nodes-sso#17]
This package should provide the Nodes' version of the AdminPanel login page. [Here](https://github.com/nodes-vapor/admin-panel-provider/blob/c0f94601d4c6a0c1d7e92b3d7b6a943bd7d01898/Resources/Views/AdminPanel/Login/index.leaf) for reference.

**Comment by steffendsommer** [comment]
Added now
